name: auto-merge

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]


jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.PA_TOKEN }}
